server {
    listen 80;
    server_name localhost;

    # 1. Phục vụ Frontend (Static Files)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Quan trọng cho React/Vite Router
    }

    # 2. Reverse Proxy cho API
    location /api/ {
        # 'pern-store-server' là tên service trong docker-compose
        proxy_pass http://server:9000; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}