apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-health-check
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health # <--- Chỉ định rõ route check sức khỏe
    port: 9000           # Port container đang chạy