apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default 
  labels:
    app.kubernetes.io/name: ecommerce-api
    app.kubernetes.io/part-of: pern-shop
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ecommerce-api
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ecommerce-api
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: pern-shop
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000

      containers:
        - name: api-server
          image: asia-southeast1-docker.pkg.dev/sapient-depot-482908-d3/docker-registry/pern-ecommerce-server:latest
          imagePullPolicy: Always
          
          ports:
            - name: http
              containerPort: 9000 
              protocol: TCP

          resources:
            requests:
              cpu: "150m"    
              memory: "256Mi"  
            limits:
              cpu: "500m"      
              memory: "256Mi"  

          env:
            - name: PORT
              value: "9000"
            - name: NODE_ENV
              value: "production"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials 
                  key: host                  
            
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: port                 

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: dbname

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: password

            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials 
                  key: smtp-from                 
            
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials 
                  key: smtp-user                

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: stripe-secret-key

            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: oauth-client-id

            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: oauth-client-secret

            - name: OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: oauth-refresh-token

            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials 
                  key: client-id                
            
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials 
                  key: client-secret                

            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: refresh-token

            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: jwt-secret

            - name: REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-credentials
                  key: jwt-refresh-secret                      

          readinessProbe:
            httpGet:
              path: /health 
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3