grafana:
  enabled: true
  
  ingress:
    enabled: true
    ingressClassName: nginx 
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

    hosts:
      - grafana.thltunneling.dpdns.org 
    
    path: /

  grafana.ini:
    server:
      domain: grafana.thltunneling.dpdns.org
      root_url: "%(protocol)s://%(domain)s/"
      serve_from_sub_path: false

prometheus:
  prometheusSpec:
    retention: 2d 
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi