version: "1.0" 
services:
  server:
    build:
      target: dev
    ports:
      - "9000:9000"  # Map cổng 9000 của host tới cổng 9000 của container để truy cập API server từ bên ngoài
    restart: always

  frontend:
    build:
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://server:9000
      - VITE_GOOGLE_CLIENT_ID=926599606710-feabn75ggmr1ofggru6mdiupq1vtl4qr.apps.googleusercontent.com
      - VITE_STRIPE_PUB_KEY=pk_test_51SnfZ7Ho4mzcNxtWRuqKSjP7gya7ZeV646uV5KxEY1riC9CRtIYFa0ulQ2NzqSigdWwd27QFLEtis1ymc8sJyhfJ00utRylTB6
      - VITE_PAYSTACK_PUB_KEY=pk_test_uuiduw984x4h4xx41489j94n
    ports:
      - "3000:3000"  # Map cổng 3000 của host tới cổng 3000 của container để truy cập frontend từ bên ngoài