version: "1.0"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server