apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: pern-ssl-cert-v3
spec:
  domains:
    - ecommerce.thltunneling.dpdns.org # <--- Thay bằng domain thật của bạn (VD: shop.toandev.com)