{{- if and .Values.secrets.externalSecrets.enabled .Values.podIdentity.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.externalSecrets.secretStore.name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: pern-ecommerce
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: pern-shop
spec:
  provider:
    azure:
      auth:
        workloadIdentity:
          audience: "api://AzureADTokenExchange"
          podRef:
            name: backend
            namespace: {{ .Values.namespace | default "default" }}
      vaultUrl: "https://{{ .Values.azure.keyVault.name }}.vault.azure.net"
      tenantID: {{ .Values.azure.managedIdentity.tenantId | quote }}
{{- end }}
