apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.externalSecrets.secretStore.name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: pern-ecommerce
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: pern-shop
spec:
  provider:
    azurekv:
      # SỬA Ở ĐÂY: Xóa toàn bộ khối 'auth' lằng nhằng, thay bằng 1 dòng này
      authType: ManagedIdentity
      
      vaultUrl: "https://{{ .Values.azure.keyVault.name }}.vault.azure.net"
      
      # Lưu ý: Chữ Id viết hoa chữ I, viết thường chữ d (tenantId chứ không phải tenantID)
      tenantId: {{ .Values.azure.managedIdentity.tenantId | quote }}
{{- end }}