{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pern-ingress
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: pern-ecommerce
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: pern-shop
    deployment.env: {{ .Values.global.environment }}
    cloud-platform: "gcp"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
{{- end }}