{{- if .Values.secrets.externalSecrets.enabled .Values.workloadIdentity.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secrets.externalSecrets.secretStore.name }}
  labels:
    app.kubernetes.io/name: pern-ecommerce
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: pern-shop
    cloud-platform: "gcp"
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gcp.cluster.clusterLocation | quote }}
          clusterName: {{ .Values.gcp.cluster.name | quote }}
          serviceAccountRef:
            name: {{ .Values.workloadIdentity.serviceAccountName }}
            namespace: {{ .Values.workloadIdentity.namespace }}
{{- end }}