apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: pern-ecommerce
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: pern-shop
data:
  VITE_GOOGLE_CLIENT_ID: {{ .Values.config.googleClientId | quote }}
  VITE_STRIPE_PUB_KEY: {{ .Values.config.stripePubKey | quote }}
  VITE_PAYSTACK_PUB_KEY: {{ .Values.config.paystackPubKey | quote }}
  VITE_API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
