apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: pernecommerce-dev
spec:
  hard:
    requests.cpu: "300m"      
    requests.memory: "512Mi"  
    limits.cpu: "1"           
    limits.memory: "1Gi"     