apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app.kubernetes.io/name: ecommerce-frontend
    app.kubernetes.io/part-of: pern-shop
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: ecommerce-frontend
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ecommerce-frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: pern-shop
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: nginx
          image: asia-southeast1-docker.pkg.dev/sapient-depot-482908-d3/docker-registry/pern-ecommerce-client:latest
          imagePullPolicy: Always # Luôn kéo bản mới nhất
          
          envFrom:
            - configMapRef:
                name: pern-config
                
          ports:
            - name: http
              containerPort: 8080 
              protocol: TCP

          resources:
            requests:
              cpu: "100m"  
              memory: "128Mi"  
            limits:
              cpu: "200m"      
              memory: "256Mi"  

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3