name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'  

env:
  PROJECT_ID: sapient-depot-482908-d3
  CLUSTER_NAME: pern-ecommerce-cluster
  GAR_LOCATION: asia-southeast1
  REPOSITORY: docker-registry
  IMAGE: pern-ecommerce-server
  DEPLOYMENT: backend
  CONTAINER: api-server
  WWORKLOAD_IDENTITY_PROVIDER: projects/926599606710/locations/global/workloadIdentityPools/github-pool/providers/github-provider

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WWORKLOAD_IDENTITY_PROVIDER }}
          service_account: 'github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Backend
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" ./server
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GAR_LOCATION }}

      - name: Deploy to GKE
        run: |-
          kubectl set image deployment/${{ env.DEPLOYMENT }} ${{ env.CONTAINER }}=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT }}