# values.yaml

# --- GLOBAL & GCP SETTINGS ---
gcp:
  projectId: "sapient-depot-482908-d3"
  clusterLocation: "asia-southeast1"
  clusterName: "pern-ecommerce-cluster"

domain: "ecommerce.thltunneling.dpdns.org"

# --- BACKEND SETTINGS ---
backend:
  replicaCount: 1
  image:
    repository: "asia-southeast1-docker.pkg.dev/sapient-depot-482908-d3/docker-registry/pern-ecommerce-server"
    tag: "latest" # Mentor Tip: Change this to a specific version (e.g., v1.0.0) in production
  resources:
    requests:
      cpu: "150m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  service:
    port: 80
    targetPort: 9000
  healthCheck:
    requestPath: "/health"

# --- SECRET MANAGEMENT SETTINGS ---
secrets:
  # The name of the JSON secret in Google Secret Manager
  gcpSecretName: "PERN-backend-secret"
  # The name of the resulting Kubernetes Secret
  k8sSecretName: "supabase-credentials"

# --- INGRESS SETTINGS ---
ingress:
  staticIpName: "pern-ingress-ip"
  sslCertName: "pern-ssl-cert-v3"
  # Frontend service configuration for Ingress routing
  frontend:
    serviceName: "frontend-svc"
    servicePort: 80

# --- FRONTEND CONFIG SETTINGS ---
# Variables for Vite (used in the ConfigMap)
frontendConfig:
  googleClientId: "926599606710-feabn75ggmr1ofggru6mdiupq1vtl4qr.apps.googleusercontent.com"
  stripePubKey: "pk_test_51SnfZ7Ho4mzcNxtWRuqKSjP7gya7ZeV646uV5KxEY1riC9CRtIYFa0ulQ2NzqSigdWwd27QFLEtis1ymc8sJyhfJ00utRylTB6"
  paystackPubKey: "pk_test_uuiduw984x4h4xx41489j94n"