apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-health-check
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    # Templated path and port
    requestPath: {{ .Values.backend.healthCheck.requestPath }}
    port: {{ .Values.backend.service.targetPort }}