apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app.kubernetes.io/name: ecommerce-api
    app.kubernetes.io/component: backend
  annotations:
    cloud.google.com/backend-config: '{"default":"backend-health-check"}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ecommerce-api
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP