apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-es
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    # Templated K8s Secret Name
    name: {{ .Values.secrets.k8sSecretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      # Templated GCP Secret Name
      key: {{ .Values.secrets.gcpSecretName }}