apiVersion: external-secrets.io/v1  # <--- BẮT BUỘC DÙNG v1 (theo kết quả explain của bạn)
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:                            # <--- Trong bản v1, cái này vẫn là 'gc'
      projectID: "sapient-depot-482908-d3"
      auth:
        workloadIdentity:
          clusterLocation: "asia-southeast1"
          clusterName: "pern-ecommerce-cluster"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets