apiVersion: external-secrets.io/v1  
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:                           
      projectID: "sapient-depot-482908-d3"
      auth:
        workloadIdentity:
          clusterLocation: "asia-southeast1"
          clusterName: "pern-ecommerce-cluster"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets