name: Deploy Backend to Azure AKS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'

env:
  ACR_NAME: pernecommerceacrdevregistry
  IMAGE: pern-ecommerce-server
  NAMESPACE: pernecommerce-dev

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Backend
        run: |
          IMAGE_TAG="${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG ./server
          docker push $IMAGE_TAG

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.AKS_KUBECONFIG }}

      - name: Deploy to AKS using Helm
        run: |
          helm upgrade pernecommerce ./helm/charts/azure \
            -f ./helm/environments/azure/values-dev.yaml \
            --set pern-ecommerce-app.backend.image.tag=${{ github.sha }} \
            -n ${{ env.NAMESPACE }} \
            --reuse-values