name: Deploy Frontend to Azure AKS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'

env:
  ACR_NAME: pernecommerceacrdevregistry
  CLUSTER_NAME: pernecommerce-aks-dev
  RESOURCE_GROUP: pernecommerce-rg
  NAMESPACE: pernecommerce-dev
  IMAGE: pern-ecommerce-client
  DEPLOYMENT: frontend
  CONTAINER: web                         # Tên container Frontend

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Đăng nhập trực tiếp vào ACR bằng Admin User
      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          IMAGE_TAG="${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG ./client
          docker push $IMAGE_TAG

      - name: Get AKS Credentials
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT }} ${{ env.CONTAINER }}=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE }}:${{ github.sha }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT }} -n ${{ env.NAMESPACE }}